export const PROPERTIES = {
  ORGANPOWER: 'organ power',
  CHEMICAL: {
    TOXIC: 'toxic',
    CORROSIVE: 'corrosive',
    CAUSTIC: 'caustic',
    ASPHYXIANT: 'asphyxiant',
  },
  FLAVOUR: {
    SALT: 'salt',
    SWEET: 'sweet',
    BITTER: 'bitter',
    SOUR: 'sour',
    UMAMI: 'umami',
    SPICY: 'spicy',
    WARM: 'warm',
    COOL: 'cool',
    ASTRINGENT: 'astringent',
    VEGETAL: 'vegetal',
    FLORAL: 'floral',
    HERBAL: 'herbal',
    PUTRID: 'putrid',
    TART: 'tart',
    EARTHY: 'earthy',
    GRASSY: 'grassy',
    NUTTY: 'nutty',
    METALLIC: 'metallic',
    GAMEY: 'gamey',
    FISHY: 'fishy',
  },
  FOODTEXTURE: {
    SQUISHY: 'squishy',
    CREAMY: 'creamy',
    CRISP: 'crisp',
    JUICY: 'juicy',
    WATERY: 'watery',
    DRY: 'dry',
    MEALY: 'mealy',
    OILY: 'oily',
    CRUNCHY: 'crunchy',
    HARD: 'hard',
    SOFT: 'soft',
    FIRM: 'firm',
    TOUGH: 'tough',
    TENDER: 'tender',
    SLIMY: 'slimy',
    STRINGY: 'stringy',
  },
  COLOUR: {
    RED: 'red',
    BLUE: 'blue',
    YELLOW: 'yellow',
    GREEN: 'green',
    ORANGE: 'orange',
    PURPLE: 'purple',
    BROWN: 'brown',
    GREY: 'grey',
    WHITE: 'white',
    BLACK: 'black',
    PINK: 'pink',
  },
  LUSTRE: 'lustre',
  RESONANCE: 'resonance',
  PHARMACEUTICAL: {
    ALCOHOLIC: 'alcoholic',
    ANALGESIC: 'analgesic',
    NARCOTIC: 'narcotic',
    NOOTROPIC: 'nootropic',
    HALLUCINAGENIC: 'hallucinagenic',
    ANAESTHETIC: 'anaesthetic',
    EUPHORIC: 'euphoric',
    STIMULANT: 'stimulant',
    DEPRESSANT: 'depressant',
  }






}

export const MATERIAL = {
  ROCK: {
    IGNEOUS: 'igneous rock',
    SEDIMENTARY: 'sedimentary rock',
    METAMORPHIC: 'metamorphic rock',
    GEM: {
      SEMIPRECIOUS: 'semiprecious gem',
      PRECIOUS: 'precious gem',
    }
  },
  METAL: {
    COMMON: 'common metal',
    UNCOMMON: 'uncommon metal',
    PRECIOUS: 'precious metal',
    ALLOY: 'metal alloy',
  },
  PLANTPART: {
    WOOD: {
      HARDWOOD: 'hardwood',
      SOFTWOOD: 'softwood',
    },
    LEAF: {
      LEAF: 'leaf',
      NEEDLE: 'needle',
      FLESHY: 'fleshy leaf',
      SPIKE: 'spike',
    },
    ROOT: {
      TAP: 'taproot',
      FIBROUS: 'fibrous root',
    },
    STEM: {
      STEM: 'stem',
      UNDERGROUND: {
        BULB: 'bulb',
        TUBER: 'tuber',
        ROOTSTALK: 'rootstalk'
      },
      AERIAL: {
        THORN: 'thorn',
        TENDRIL: 'tendril',
      },
    },
    FLOWER: 'flower',
    CONE: 'cone',
    BARK: 'bark',
    SEED: 'seed',
    SAP: 'sap',
    FRUIT: 'fruit',
  },
  ANIMALPART: {
    STRUCTURE: {
      BONE: {
        HOLLOW: 'hollow bone',
        SOFT: 'soft bone',
        SOLID: 'solid bone',
        DENSE: 'dense bone',
      },
      SKIN: 'skin',
      MUSCLE: 'muscle',
      FAT: 'fat',
      FUR: 'fur',
      SCALES: 'scales',
      FEATHER: 'feather',
      SHELL: 'shell',
    },
    SECRETION: {
      BLOOD: 'blood',
      SPIT: 'spit',
      MILK: 'milk',
      VENOM: 'venom',
      POISON: 'poison',
      INK: 'ink',
      EGG: 'egg',
    },
    SENSOR: {
      EYE: 'eye',
      EAR: 'ear',
      NOSE: 'nose',
      TOUCH: 'touch',
    },
    WEAPONS: {
      TOOTH: 'tooth',
      CLAW: 'claw',
      HORN: 'horn',
    },
    ORGAN: {
      BRAIN: 'brain',
      HEART: 'heart',
      LUNG: 'lung',
      STOMACH: 'stomach',
      LIVER: 'liver',
      KIDNEY: 'kidney',
      INTESTINE: 'intestine',
      GIZZARD: 'gizzard',
    },
    LIMB: {
      HEAD: 'head',
      ARM: 'arm',
      LEG: 'leg',
      WING: 'wing',
      TENTACLE: 'tentacle',
      TAIL: 'tail',
    },
  },
  TEXTILE: {
    FIBRE: 'fibre',
    SHEET: 'sheet',
    ROPE: 'rope',
  },
  CERAMIC: 'ceramic',
  GLASS: 'glass',
  DIRT: 'dirt',
  RUBBER: 'rubber',
}

export const LIFE = {
  ANIMAL: {
    BIRD: 'bird',
    BEAST: {
      FURRY: 'furry beast',
      SCALED: 'scaled beast',
    },
    FISH: 'fish',
    BUG: 'bug',
    JELLY: 'jelly',
  },
  PLANT: {
    TREE: {
      HARDWOOD: 'hardwood tree',
      SOFTWOOD: 'softwood tree',
    },
    SHRUB: 'shrub',
    GRASS: 'grass',
    SUCCULENT: 'succulent',
    MOSS: 'moss',
    VEGETABLE: 'vegetable',
    FLORAL: 'floral',
    SEAGRASS: 'seagrass',
    SEAWEED: 'seaweed',
  }
}

export const ORGANPOWER = {
  [MATERIAL.ANIMALPART.SENSOR.EYE]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */ { average: 6, range: 2, },
    [LIFE.ANIMAL.BEAST.SCALED]:/**/ { average: 4, range: 2, },
    [LIFE.ANIMAL.BIRD]:/*        */ { average: 8, range: 2, },
    [LIFE.ANIMAL.FISH]:/*        */ { average: 4, range: 1, },
    [LIFE.ANIMAL.BUG]:/*         */ { average: 5, range: 4, },
    [LIFE.ANIMAL.JELLY]:/*       */ { average: 1, range: 1, },
  },
  [MATERIAL.ANIMALPART.SENSOR.EAR]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */ { average: 6, range: 4, },
    [LIFE.ANIMAL.BEAST.SCALED]:/**/ { average: 4, range: 2, },
    [LIFE.ANIMAL.BIRD]:/*        */ { average: 6, range: 2, },
    [LIFE.ANIMAL.FISH]:/*        */ { average: 3, range: 1, },
    [LIFE.ANIMAL.BUG]:/*         */ { average: 2, range: 1, },
    [LIFE.ANIMAL.JELLY]:/*       */ { average: 1, range: 1, },
  },
  [MATERIAL.ANIMALPART.SENSOR.NOSE]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */ { average: 8, range: 2, },
    [LIFE.ANIMAL.BEAST.SCALED]:/**/ { average: 7, range: 3, },
    [LIFE.ANIMAL.BIRD]:/*        */ { average: 4, range: 1, },
    [LIFE.ANIMAL.FISH]:/*        */ { average: 3, range: 2, },
    [LIFE.ANIMAL.BUG]:/*         */ { average: 3, range: 1, },
    [LIFE.ANIMAL.JELLY]:/*       */ { average: 1, range: 1, },
  },
  [MATERIAL.ANIMALPART.SENSOR.TOUCH]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */ { average: 7, range: 2, },
    [LIFE.ANIMAL.BEAST.SCALED]:/**/ { average: 7, range: 3, },
    [LIFE.ANIMAL.BIRD]:/*        */ { average: 5, range: 1, },
    [LIFE.ANIMAL.FISH]:/*        */ { average: 3, range: 2, },
    [LIFE.ANIMAL.BUG]:/*         */ { average: 2, range: 1, },
    [LIFE.ANIMAL.JELLY]:/*       */ { average: 1, range: 1, },
  },
  [MATERIAL.ANIMALPART.ORGAN.BRAIN]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */ { average: 7, range: 3, },
    [LIFE.ANIMAL.BEAST.SCALED]:/**/ { average: 5, range: 3, },
    [LIFE.ANIMAL.BIRD]:/*        */ { average: 6, range: 2, },
    [LIFE.ANIMAL.FISH]:/*        */ { average: 4, range: 2, },
    [LIFE.ANIMAL.BUG]:/*         */ { average: 2, range: 2, },
    [LIFE.ANIMAL.JELLY]:/*       */ { average: 1, range: 1, },
  },
}

export const PROPERTYMATRIX = {
  [MATERIAL.ANIMALPART.STRUCTURE.MUSCLE]: {
    [LIFE.ANIMAL.BEAST.FURRY]:/* */[{ prop: PROPERTIES.FOODTEXTURE.FIRM, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.GAMEY, chance: 0.4, }, { prop: PROPERTIES.FLAVOUR.GRASSY, chance: 0.1, },],
    [LIFE.ANIMAL.BEAST.SCALED]:/**/[{ prop: PROPERTIES.FOODTEXTURE.FIRM, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.GAMEY, chance: 0.3, },],
    [LIFE.ANIMAL.BIRD]:/*        */[{ prop: PROPERTIES.FOODTEXTURE.FIRM, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.GAMEY, chance: 0.3, },],
    [LIFE.ANIMAL.FISH]:/*        */[{ prop: PROPERTIES.FOODTEXTURE.SOFT, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.FISHY, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.SALT, chance: 0.3, },],
    [LIFE.ANIMAL.BUG]:/*         */[{ prop: PROPERTIES.FOODTEXTURE.SLIMY, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, },{ prop: PROPERTIES.FLAVOUR.BITTER, chance: 0.6, },{ prop: PROPERTIES.CHEMICAL.TOXIC, chance: 0.2, },],
    [LIFE.ANIMAL.JELLY]:/*       */[{ prop: PROPERTIES.FOODTEXTURE.SLIMY, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.UMAMI, chance: 1.1, }, { prop: PROPERTIES.FLAVOUR.SWEET, chance: 0.1, },],
  },
  [MATERIAL.ANIMALPART.STRUCTURE.FAT]: {},
  [MATERIAL.ANIMALPART.ORGAN.BRAIN]: {},
  [MATERIAL.ANIMALPART.ORGAN.HEART]: {},
  [MATERIAL.ANIMALPART.ORGAN.LUNG]: {},
  [MATERIAL.ANIMALPART.ORGAN.STOMACH]: {},
  [MATERIAL.ANIMALPART.ORGAN.LIVER]: {},
  [MATERIAL.ANIMALPART.ORGAN.KIDNEY]: {},
  [MATERIAL.ANIMALPART.ORGAN.INTESTINE]: {},
  [MATERIAL.ANIMALPART.ORGAN.GIZZARD]: {},
  [MATERIAL.ANIMALPART.SECRETION.BLOOD]: {},
  [MATERIAL.ANIMALPART.SECRETION.SPIT]: {},
  [MATERIAL.ANIMALPART.SECRETION.MILK]: {},
  [MATERIAL.ANIMALPART.SECRETION.EGG]: {},
  [MATERIAL.ANIMALPART.SECRETION.VENOM]: {},
  [MATERIAL.ANIMALPART.SECRETION.POISON]: {},
  [MATERIAL.ANIMALPART.SECRETION.INK]: {},
  [MATERIAL.PLANTPART.WOOD.HARDWOOD]: {},
  [MATERIAL.PLANTPART.WOOD.SOFTWOOD]: {},
  [MATERIAL.PLANTPART.LEAF.FLESHY]: {},
  [MATERIAL.PLANTPART.LEAF.LEAF]: {},
  [MATERIAL.PLANTPART.LEAF.NEEDLE]: {},
  [MATERIAL.PLANTPART.LEAF.SPIKE]: {},
  [MATERIAL.PLANTPART.ROOT.TAP]: {},
  [MATERIAL.PLANTPART.ROOT.FIBROUS]: {},
  [MATERIAL.PLANTPART.STEM.STEM]: {},
  [MATERIAL.PLANTPART.STEM.UNDERGROUND.BULB]: {},
  [MATERIAL.PLANTPART.STEM.UNDERGROUND.ROOTSTALK]: {},
  [MATERIAL.PLANTPART.STEM.UNDERGROUND.TUBER]: {},
  [MATERIAL.PLANTPART.STEM.AERIAL.THORN]: {},
  [MATERIAL.PLANTPART.STEM.AERIAL.TENDRIL]: {},
  [MATERIAL.PLANTPART.FLOWER]: {},
  [MATERIAL.PLANTPART.CONE]: {},
  [MATERIAL.PLANTPART.BARK]: {},
  [MATERIAL.PLANTPART.SEED]: {},
  [MATERIAL.PLANTPART.SAP]: {},
  [MATERIAL.PLANTPART.FRUIT]: {},
}
